# Generated by Django 5.0.6 on 2024-07-13 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=10)),
                ('pro_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pro_img', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='d_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df_name', models.CharField(max_length=10)),
                ('dl_name', models.CharField(max_length=15)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_adrs', models.CharField(max_length=50)),
                ('d_phno', models.IntegerField()),
                ('d_img', models.FileField(upload_to='')),
                ('d_lcnc', models.FileField(upload_to='')),
                ('d_bio', models.FileField(upload_to='')),
                ('d_username', models.CharField(max_length=10, unique=True)),
                ('d_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default=1)),
                ('t_price', models.FloatField()),
                ('oaddress', models.CharField(max_length=80)),
                ('ocity', models.CharField(max_length=20)),
                ('odistrict', models.CharField(max_length=20)),
                ('opincode', models.IntegerField()),
                ('ophone', models.IntegerField()),
                ('ofname', models.CharField(default='', max_length=30)),
                ('olname', models.CharField(default='', max_length=30)),
                ('additional', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(default=0, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='u_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('u_phno', models.IntegerField()),
                ('u_img', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('u_address', models.CharField(max_length=100)),
                ('u_district', models.CharField(max_length=20)),
                ('u_city', models.CharField(max_length=20)),
                ('u_pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('orderdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.add_product')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset_delboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.d_register')),
            ],
        ),
        migrations.CreateModel(
            name='Single_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_fname', models.CharField(max_length=20)),
                ('so_lname', models.CharField(max_length=20)),
                ('so_email', models.EmailField(max_length=254)),
                ('so_phone', models.IntegerField()),
                ('so_address', models.TextField()),
                ('so_district', models.CharField(max_length=20)),
                ('so_city', models.CharField(max_length=20)),
                ('so_pincode', models.IntegerField()),
                ('add_message', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=150, null=True)),
                ('order_id', models.CharField(max_length=150)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.add_product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.u_register')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.u_register')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.u_register'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.add_product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.u_register')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.add_product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.u_register')),
            ],
        ),
    ]
