# Generated by Django 5.0.6 on 2024-07-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderdet',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='single_booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='single_booking',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='orderitem',
        ),
        migrations.DeleteModel(
            name='Single_Booking',
        ),
    ]
