# Generated by Django 5.0.6 on 2024-08-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatapp', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meatapp.d_register')),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordReset_delboy',
        ),
    ]
