# Generated by Django 5.0.6 on 2024-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatapp', '0004_passwordresets_delete_passwordreset_delboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_register',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
