# Generated by Django 5.0.6 on 2024-08-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatapp', '0005_d_register_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_register',
            old_name='is_accepted',
            new_name='accepted',
        ),
    ]
