# Generated by Django 5.0.6 on 2024-08-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatapp', '0006_rename_is_accepted_d_register_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_register',
            name='accepted',
        ),
    ]
