# Generated by Django 5.0.6 on 2024-08-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatapp', '0007_remove_d_register_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_register',
            name='duty_status',
            field=models.CharField(choices=[('in-duty', 'In-Duty'), ('off-duty', 'Off-Duty'), ('unavailable', 'Unavailable')], default='off-duty', max_length=20),
        ),
        migrations.AddField(
            model_name='d_register',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meatapp.d_register'),
        ),
    ]
