# Generated by Django 5.0.6 on 2024-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatapp', '0009_remove_d_register_duty_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_person',
        ),
        migrations.AlterField(
            model_name='d_register',
            name='d_status',
            field=models.CharField(choices=[('available', 'Available'), ('in-duty', 'In-Duty'), ('off-duty', 'Off-Duty')], default='off-duty', max_length=10),
        ),
    ]
