# Generated by Django 5.0.6 on 2024-08-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatapp', '0010_remove_order_delivery_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meatapp.d_register'),
        ),
    ]
